# Generated by Django 3.2.12 on 2022-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_make', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='computer_make',
            name='make',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
