# Generated by Django 3.2.12 on 2022-05-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220523_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_model', models.CharField(max_length=40)),
                ('c_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_make')),
            ],
        ),
    ]
