# Generated by Django 3.2.12 on 2022-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_computer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_model',
            name='c_typye',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Server', 'Server')], default='Desktop', max_length=30),
        ),
    ]
