# Generated by Django 3.2.12 on 2022-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_computer_model_c_typye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_model',
            name='c_typye',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Server', 'Server')], max_length=30),
        ),
    ]
