# Generated by Django 3.2.12 on 2022-05-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_computer_model_c_typye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer_model',
            old_name='c_typye',
            new_name='c_type',
        ),
        migrations.CreateModel(
            name='Display_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(choices=[('CRT', 'CRT'), ('LCD', 'LCD'), ('LED', 'LED')], default='LCD', max_length=30)),
                ('d_model', models.CharField(max_length=40)),
                ('d_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_make')),
            ],
        ),
    ]
