# Generated by Django 3.2.12 on 2022-05-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220523_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_type', models.CharField(choices=[('phone', 'phone'), ('camera', 'camera'), ('gps', 'gps')], default='phone', max_length=30)),
                ('mmodel', models.CharField(max_length=50)),
                ('mmake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mobile_make')),
            ],
        ),
    ]
