# Generated by Django 3.2.12 on 2022-05-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_printer_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_model',
            old_name='mmake',
            new_name='m_make',
        ),
        migrations.RenameField(
            model_name='mobile_model',
            old_name='mmodel',
            new_name='m_model',
        ),
        migrations.RenameField(
            model_name='mobile_model',
            old_name='mobile_type',
            new_name='m_type',
        ),
    ]
