# Generated by Django 3.2.12 on 2022-05-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220524_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_model', models.CharField(max_length=50)),
                ('s_type', models.CharField(choices=[('flatbed', 'flatbed'), ('sheet-fed', 'sheet-fed')], default='flatbed', max_length=50)),
                ('s_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_make')),
            ],
        ),
    ]
