# Generated by Django 3.2.12 on 2022-05-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_scanner_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projector_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_model', models.CharField(max_length=50)),
                ('prj_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_make')),
            ],
        ),
    ]
