# Generated by Django 3.2.12 on 2022-05-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_projector_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_fam', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Apple', 'Apple')], max_length=30)),
                ('os_system', models.CharField(max_length=50)),
                ('os_architecture', models.IntegerField(max_length=64)),
            ],
        ),
    ]
