# Generated by Django 3.2.12 on 2022-05-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_ossystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ossystem',
            name='os_architecture',
            field=models.CharField(choices=[('32-bit', '32-bit'), ('64-bit', '64-bit')], default='64-bit', max_length=10),
        ),
    ]
