# Generated by Django 3.2.12 on 2022-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_building_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='division',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
