# Generated by Django 3.2.12 on 2022-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220524_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_make', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Other', 'Other')], default='Intel', max_length=10)),
                ('cpu', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
