# Generated by Django 3.2.12 on 2022-05-24 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('office', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('spacecode', models.CharField(blank=True, default='00000', max_length=15, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.building')),
            ],
        ),
    ]
