# Generated by Django 3.2.12 on 2022-05-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, default='7209', max_length=10)),
                ('email', models.EmailField(blank=True, default='@ub.ac.bw', max_length=254)),
                ('mobile', models.CharField(blank=True, default=7100000, max_length=10)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Professor', 'Professo'), ('-', '-')], default='-', max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('academic', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.division')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
