# Generated by Django 3.2.12 on 2022-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_custodian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
