# Generated by Django 3.2.12 on 2022-05-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_custodian_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='office',
            field=models.CharField(blank=True, default='7200', max_length=10),
        ),
    ]
