# Generated by Django 3.2.12 on 2022-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_custodian_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Professor', 'Professor'), ('-', '-')], default='-', max_length=30),
        ),
    ]
