# Generated by Django 3.2.12 on 2022-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_custodian_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Support', 'Support'), ('Student', 'Student')], default='Academic', max_length=20),
        ),
    ]
