# Generated by Django 3.2.12 on 2022-05-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_custodian_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodian',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='custodian',
            name='student',
        ),
        migrations.RemoveField(
            model_name='custodian',
            name='support',
        ),
    ]
