# Generated by Django 3.2.12 on 2022-05-30 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20220525_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acode', models.CharField(blank=True, max_length=7, unique=True)),
                ('sno', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_issued', models.DateField(blank=True, default='2022-01-01', null=True)),
                ('date_captured', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('comments', models.CharField(blank=True, default='n/a', max_length=70)),
                ('asset_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.custodian')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
        ),
    ]
