# Generated by Django 3.2.12 on 2022-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='operative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
