# Generated by Django 3.2.12 on 2022-06-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20220601_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='comp_sno',
        ),
    ]
