# Generated by Django 3.2.12 on 2022-06-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_computer_comp_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='computer',
            name='comp_cspeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
