# Generated by Django 3.2.12 on 2022-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20220601_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
