# Generated by Django 3.2.12 on 2022-06-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_asset_date_issued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodian',
            options={'ordering': ['surname']},
        ),
    ]
