# Generated by Django 3.2.12 on 2022-06-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_custodian_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='computer_model',
            unique_together={('c_make', 'c_model')},
        ),
    ]
