# Generated by Django 3.2.12 on 2022-06-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_computer_model_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer_model',
            options={'ordering': ['c_make', 'c_model']},
        ),
    ]
