# Generated by Django 3.2.12 on 2022-06-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_computer_model_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('block', 'office')},
        ),
    ]
