# Generated by Django 3.2.12 on 2022-06-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='spacecode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
