# Generated by Django 3.2.12 on 2022-06-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_location_spacecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custodian',
            old_name='Department',
            new_name='department',
        ),
    ]
