# Generated by Django 3.2.12 on 2022-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_rename_department_custodian_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
