# Generated by Django 3.2.12 on 2022-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
