# Generated by Django 3.2.12 on 2022-06-15 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20220614_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.asset')),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.custodian')),
            ],
        ),
    ]
