# Generated by Django 3.2.12 on 2022-06-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset'),
        ),
    ]
