# Generated by Django 3.2.12 on 2022-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_loan_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
