# Generated by Django 3.2.12 on 2022-06-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_loan_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('monitor_type', models.CharField(choices=[('CRT Monitor', 'CRT Monitor'), ('LCD Monitor', 'LCD Monitor'), ('LED Monitor', 'LED Monitor')], default='LCD Monitor', max_length=15)),
                ('monitor_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.display_model')),
                ('monitor_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.project')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
