# Generated by Django 3.2.12 on 2022-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, default='Display', max_length=50, null=True),
        ),
    ]
