# Generated by Django 3.2.12 on 2022-06-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_desktop'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='form_factor',
            field=models.CharField(choices=[('SFF', 'SFF'), ('Tower', 'Tower'), ('Mini', 'Mini PC')], default='SFF', max_length=30),
        ),
    ]
