# Generated by Django 3.2.12 on 2022-06-20 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_desktop_form_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='ram',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
