# Generated by Django 3.2.12 on 2022-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_asset_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DType',
            fields=[
                ('dtype', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
