# Generated by Django 3.2.12 on 2022-06-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(default='Desktop', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dtype'),
        ),
    ]
