# Generated by Django 3.2.12 on 2022-06-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, default='Computer', max_length=50, null=True),
        ),
    ]
