# Generated by Django 3.2.12 on 2022-06-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_alter_asset_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
    ]
