# Generated by Django 3.2.12 on 2022-06-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_remove_asset_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
