# Generated by Django 3.2.12 on 2022-06-23 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_delete_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ram', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('laptop_type', models.CharField(choices=[('laptop', 'Laptop'), ('mini', 'Mini Laptop'), ('Tablet', 'Tablet')], default='Laptop', max_length=30)),
                ('laptop_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ossystem')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cpu')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
