# Generated by Django 3.2.12 on 2022-06-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='laptop_mmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_model'),
        ),
    ]
