# Generated by Django 3.2.12 on 2022-06-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_laptop_laptop_mmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dtype'),
        ),
    ]
