# Generated by Django 3.2.12 on 2022-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='form_factor',
            field=models.CharField(choices=[('SFF', 'SFF'), ('Tower', 'Tower'), ('Mini', 'Mini PC'), ('al-in-one', 'All-In-One'), ('other', 'Other')], default='SFF', max_length=30),
        ),
    ]
