# Generated by Django 3.2.12 on 2022-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_desktop_form_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ossystem',
            name='os_type',
            field=models.CharField(choices=[('client', 'client'), ('server', 'server')], default='client', max_length=10),
        ),
    ]
