# Generated by Django 3.2.12 on 2022-06-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_ossystem_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
