# Generated by Django 3.2.12 on 2022-06-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_asset_asset_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_mmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_model'),
        ),
    ]
