# Generated by Django 3.2.12 on 2022-06-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_laptop_laptop_mmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.custodian'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.project'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.location'),
        ),
    ]
