# Generated by Django 3.2.12 on 2022-06-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20220629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.laptop'),
        ),
    ]
