# Generated by Django 3.2.12 on 2022-06-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_alter_loan_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_mmodel',
            field=models.ForeignKey(limit_choices_to={'c_type': 'Laptop'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_model'),
        ),
    ]
