# Generated by Django 3.2.12 on 2022-06-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_alter_laptop_laptop_mmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='desktop_mmodel',
            field=models.ForeignKey(limit_choices_to={'c_type': 'Desktop'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_model'),
        ),
    ]
