# Generated by Django 3.2.12 on 2022-06-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_alter_desktop_desktop_mmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='desktop_project',
        ),
    ]
