# Generated by Django 3.2.12 on 2022-06-30 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_remove_desktop_desktop_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ram', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('form_factor', models.CharField(choices=[('Tower', 'Tower'), ('rack-Mount', 'rack-mount'), ('blade', 'blade')], default='rack-mount', max_length=30)),
                ('raid', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fqdn', models.CharField(blank=True, max_length=30)),
                ('DNS', models.BooleanField(default=False)),
                ('File', models.BooleanField(default=False)),
                ('DHCP', models.BooleanField(default=False)),
                ('other_roles', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.ForeignKey(blank=True, limit_choices_to={'os_type': 'server'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ossystem')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cpu')),
                ('server_mmodel', models.ForeignKey(limit_choices_to={'c_type': 'server'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_model')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
