# Generated by Django 3.2.12 on 2022-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_ip',
            field=models.GenericIPAddressField(default='168.167.30.166'),
        ),
    ]
