# Generated by Django 3.2.12 on 2022-06-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_server_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
