# Generated by Django 3.2.12 on 2022-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_alter_server_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='decommissioned',
            field=models.BooleanField(default=True),
        ),
    ]
