# Generated by Django 3.2.12 on 2022-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_server_decommissioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
