# Generated by Django 3.2.12 on 2022-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_asset_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='acode',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
