# Generated by Django 3.2.12 on 2022-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_asset_acode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
