# Generated by Django 3.2.12 on 2022-07-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_asset_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('usage', models.CharField(choices=[('local', 'local'), ('shared', 'shared'), ('network', 'network')], default='local', max_length=15)),
                ('color', models.CharField(choices=[('color', 'color'), ('monochrome', 'monochrome')], default='monochrome', max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
