# Generated by Django 3.2.12 on 2022-07-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='printer_pmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.printer_model'),
        ),
    ]
