# Generated by Django 3.2.12 on 2022-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_printer_printer_pmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ossystem',
            name='os_fam',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Apple', 'Apple'), ('WMware', 'VMWare')], max_length=30),
        ),
    ]
