# Generated by Django 3.2.12 on 2022-07-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_alter_ossystem_os_fam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='other_roles',
            new_name='roles',
        ),
    ]
