# Generated by Django 3.2.12 on 2022-07-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_rename_other_roles_server_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='decommissioned',
            new_name='decomissioned',
        ),
    ]
