# Generated by Django 3.2.12 on 2022-07-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_rename_decommissioned_server_decomissioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='decomissioned',
        ),
    ]
