# Generated by Django 3.2.12 on 2022-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_server_decomissioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='obolete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acode', models.CharField(blank=True, max_length=7, unique=True)),
                ('sno', models.CharField(blank=True, max_length=30, unique=True)),
                ('other_desc', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('working ', 'working'), ('not working', 'not working')], default='not working', max_length=20)),
                ('registered', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
