# Generated by Django 3.2.12 on 2022-07-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_obolete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='obolete',
            new_name='obsolete',
        ),
    ]
