# Generated by Django 3.2.12 on 2022-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_rename_obolete_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsolete',
            name='description',
            field=models.CharField(choices=[('---', '---'), ('Desktop', 'Desktop'), ('Display', 'Display'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Projector', 'Projector'), ('Switch', 'Switch'), ('TV', 'TV')], default='---', max_length=30),
        ),
    ]
