# Generated by Django 3.2.12 on 2022-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_obsolete_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obsolete',
            old_name='description',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='obsolete',
            old_name='other_desc',
            new_name='make_model',
        ),
        migrations.AddField(
            model_name='obsolete',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=5, null=True),
        ),
    ]
