# Generated by Django 3.2.12 on 2022-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_alter_obsolete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsolete',
            name='device',
            field=models.CharField(choices=[('---', '---'), ('Desktop', 'Desktop'), ('Display', 'Display'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Projector', 'Projector'), ('Switch', 'Switch'), ('TV', 'TV'), ('board', 'board'), ('other', 'other')], default='---', max_length=30),
        ),
    ]
