# Generated by Django 3.2.12 on 2022-07-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_alter_obsolete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsolete',
            name='make_model',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
