# Generated by Django 3.2.12 on 2022-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_alter_obsolete_make_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsolete',
            name='sno',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
