# Generated by Django 3.2.12 on 2022-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_alter_obsolete_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsolete',
            name='acode',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
