# Generated by Django 3.2.12 on 2022-07-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_alter_obsolete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('scanner_type', models.CharField(choices=[('flatbed', 'flatbed'), ('feeder', 'feeder')], default='flatbed', max_length=30)),
                ('scanner_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.scanner_model')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
