# Generated by Django 3.2.12 on 2022-07-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('projector_type', models.CharField(choices=[('LCD', 'LCD'), ('LED', 'LED')], default='LED', max_length=30)),
                ('projector_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projector_model')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset', models.Model),
        ),
    ]
