# Generated by Django 3.2.12 on 2022-07-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_projector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operative', models.BooleanField(default=True)),
                ('used', models.BooleanField(default=True)),
                ('obsolete', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('mobile_code', models.CharField(blank=True, max_length=7, unique=True)),
                ('IMEI', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mb_model', models.CharField(blank=True, max_length=25)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('mb_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mobile_make')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
