# Generated by Django 3.2.12 on 2022-07-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='comments',
        ),
        migrations.AddField(
            model_name='phone',
            name='mb_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.custodian'),
        ),
        migrations.AddField(
            model_name='phone',
            name='mb_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.project'),
        ),
    ]
