# Generated by Django 3.2.12 on 2022-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_auto_20220727_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
