# Generated by Django 3.2.12 on 2022-07-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_phone_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='mobile_code',
            new_name='mb_acode',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='comments',
            new_name='mb_comments',
        ),
    ]
