# Generated by Django 3.2.12 on 2022-07-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_auto_20220727_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Asset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.asset')),
                ('om_make', models.CharField(blank=True, max_length=100)),
                ('om_model', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.asset',),
        ),
    ]
