# Generated by Django 3.2.12 on 2022-07-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_other_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_asset',
            name='om_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.computer_make'),
        ),
    ]
