# Generated by Django 3.2.12 on 2022-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_alter_other_asset_om_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
    ]
