# Generated by Django 3.2.12 on 2022-09-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20220902_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='device',
        ),
        migrations.AddField(
            model_name='loan',
            name='loaned_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset'),
        ),
    ]
