# Generated by Django 3.2.12 on 2022-09-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_auto_20220902_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaned_asset',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset'),
        ),
    ]
