# Generated by Django 3.2.12 on 2022-09-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_alter_loan_loaned_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loaned_asset',
        ),
        migrations.AddField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='dashboard.laptop'),
        ),
    ]
