# Generated by Django 3.2.12 on 2022-09-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20220902_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.laptop'),
        ),
    ]
