# Generated by Django 3.2.12 on 2022-09-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_alter_loan_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
