# Generated by Django 3.2.12 on 2022-09-02 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(limit_choices_to={'loanable': True}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset')),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.custodian')),
            ],
        ),
    ]
