# Generated by Django 3.2.12 on 2024-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='drive_size',
            field=models.CharField(choices=[('250GB', '250GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], default='500GB', max_length=30),
        ),
        migrations.AddField(
            model_name='laptop',
            name='drive_size',
            field=models.CharField(choices=[('250GB', '250GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], default='500GB', max_length=30),
        ),
        migrations.AddField(
            model_name='server',
            name='drive_size',
            field=models.CharField(choices=[('250GB', '250GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], default='500GB', max_length=30),
        ),
    ]
