# Generated by Django 3.2.12 on 2024-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20240527_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='faculty',
            field=models.CharField(default='ORI', max_length=20),
        ),
    ]
