# Generated by Django 3.2.12 on 2024-05-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_custodian_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='division',
            new_name='name',
        ),
    ]
