# Generated by Django 3.2.12 on 2024-05-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_rename_division_division_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custodian',
            old_name='department',
            new_name='division',
        ),
    ]
